FROM node:22-alpine

WORKDIR /app

COPY packages/frontend/package.json packages/frontend/package-lock.json ./
RUN npm ci

COPY packages/frontend/ .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
