"use client"

import { useEffect, useState, useRef } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { useAuthStore } from "@/lib/store/auth-store"
import * as authApi from "@/lib/api/auth"
import * as unlearningApi from "@/lib/api/unlearning"
import {
  Send,
  Plus,
  Trash2,
  ShieldCheck,
  Zap,
  Globe,
  Paperclip,
  Activity,
  AlertCircle,
} from "lucide-react"

interface Message {
  id: string
  sender: "user" | "assistant"
  text: string
  timestamp: Date
  proof?: {
    root: string
    signature: string
    algorithm: string
    status: string
  }
}

export default function DashboardPage() {
  const { user } = useAuthStore()
  const router = useRouter()
  
  // Existing stats counters
  const [eventCount, setEventCount] = useState(0)
  const [requestCount, setRequestCount] = useState(0)
  const [pendingCount, setPendingCount] = useState(0)
  const [completedCount, setCompletedCount] = useState(0)

  // Chat State
  const [chatActive, setChatActive] = useState(false)
  const [inputMessage, setInputMessage] = useState("")
  const [messages, setMessages] = useState<Message[]>([])
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    authApi.getAuditEvents({ page_size: 1 }).then((res) => {
      setEventCount(res.meta.total)
    }).catch((err) => console.error("Failed to fetch audit events:", err))

    unlearningApi.listRequests({ page_size: 1 }).then((res) => {
      setRequestCount(res.meta.total)
    }).catch((err) => console.error("Failed to fetch request count:", err))

    unlearningApi.listRequests({ page_size: 1, status: "pending" }).then((res) => {
      setPendingCount(res.meta.total)
    }).catch((err) => console.error("Failed to fetch pending count:", err))

    unlearningApi.listRequests({ page_size: 1, status: "completed" }).then((res) => {
      setCompletedCount(res.meta.total)
    }).catch((err) => console.error("Failed to fetch completed count:", err))
  }, [])

  // Auto scroll to bottom of chat
  useEffect(() => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: "smooth" })
    }
  }, [messages, isTyping])

  if (!user) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <div className="animate-spin h-8 w-8 border-4 border-[var(--brand)] border-t-transparent rounded-full" />
      </div>
    )
  }

  const handleSendMessage = async (textToSend: string) => {
    if (!textToSend.trim()) return

    const userMsg: Message = {
      id: Math.random().toString(36).substring(7),
      sender: "user",
      text: textToSend,
      timestamp: new Date(),
    }

    setMessages((prev) => [...prev, userMsg])
    setInputMessage("")
    setChatActive(true)
    setIsTyping(true)

    // Simulate response delay
    setTimeout(() => {
      let replyText = ""
      let proofData: any = undefined
      const query = textToSend.toLowerCase()

      if (query.includes("delete") || query.includes("unlearn") || query.includes("remove")) {
        replyText = `I can assist you with initiating and tracking machine unlearning requests. VeriUnlearn implements SISA (Sharded retraining), Influence Functions, and Certified Removal algorithms. 

You can configure deletion requests to automatically trigger proofs. Below is a live simulation of a cryptographic unlearning proof generated by our ML Engine:`
        proofData = {
          root: "0x7a8df2cb45e9821864193561bd8c8a14b98fa315d0263f92",
          signature: "Ed25519 (0xbf92a54ce...)",
          algorithm: "Groth16 zk-SNARK",
          status: "SUCCESS / VERIFIED",
        }
      } else if (query.includes("verify") || query.includes("proof") || query.includes("zksnark")) {
        replyText = `VeriUnlearn supports double-layer cryptographic verification:
1. **Merkle Trees:** Deletion steps are added as leaves. The root is verified using SHA-256 inclusion paths.
2. **zk-SNARKs:** Zero-knowledge proofs are generated using a simulated Groth16 Bn254 protocol to guarantee that a leaf was correctly deleted without exposing other logs or user IDs.

To test this, click **"Verify Cryptographic Proof"** on the quick-action cards, or view any completed unlearning request in the workspace.`
      } else if (query.includes("audit") || query.includes("log") || query.includes("history")) {
        replyText = `The **Audit Log** is a secure, tamper-evident hash-chain ledger. 
Each audit entry contains details of the event (IP, role, request details) along with the hash of the preceding entry:
\`\`\`bash
Event_i_Hash = SHA256(Event_i_Data + Preceding_Hash)
\`\`\`
Every 6 hours, the system hashes the root and anchors it to our blockchain anchoring service, assuring full immutability for compliance officers.`
      } else if (query.includes("security") || query.includes("mia") || query.includes("privacy")) {
        replyText = `VeriUnlearn evaluates the quality of unlearning using two security tests:
- **Membership Inference Attacks (MIA):** Simulates confidences and loss attack thresholds to ensure the target training data cannot be detected as part of the model.
- **Differential Privacy (DP):** Evaluates privacy bounds $(\\epsilon, \\delta)$ under certified removal to ensure noise addition matches GDPR requirements.`
      } else {
        replyText = `I am the VeriUnlearn Compliance & Unlearning Assistant. I can help you with:
- **Requesting data deletion** across shards (SISA)
- **Checking cryptographic proofs** and certificates
- **Auditing logs** with tamper-evident chain verification
- **Monitoring compliance webhooks**

Please select one of the suggestions or type a query (e.g., *"How do I verify a deletion proof?"* or *"Initiate unlearning"*).`
      }

      const assistantMsg: Message = {
        id: Math.random().toString(36).substring(7),
        sender: "assistant",
        text: replyText,
        timestamp: new Date(),
        proof: proofData,
      }

      setMessages((prev) => [...prev, assistantMsg])
      setIsTyping(false)
    }, 1200)
  }

  const promptSuggestions = [
    {
      title: "Initiate data deletion request",
      subtitle: "Honors the GDPR Right to be Forgotten",
      action: "Initiate a new unlearning request via SISA or certified removal",
    },
    {
      title: "Verify cryptographic proof of deletion",
      subtitle: "Validate Merkle inclusion proofs & signatures",
      action: "How do I verify a deletion proof and check its certificate?",
    },
    {
      title: "Check system security & privacy leakages",
      subtitle: "Membership Inference Attacks & DP estimates",
      action: "Evaluate MIA protection and differential privacy status",
    },
    {
      title: "View tamper-evident audit log events",
      subtitle: "Verify hash chain anchoring integrity",
      action: "Tell me about the audit log chain and blockchain anchoring",
    },
  ]

  const handleResetChat = () => {
    setMessages([])
    setChatActive(false)
  }

  return (
    <div className="flex-1 flex flex-col relative h-full bg-[var(--bg-app)] text-[var(--text-primary)]">
      
      {/* Scrollable Chat / Workspace Area */}
      <div className="flex-1 overflow-y-auto px-4 py-8 md:px-0">
        <div className="max-w-2xl mx-auto space-y-8 pb-32">
          
          {!chatActive ? (
            // Central Intro Workspace (ChatGPT Style)
            <div className="flex flex-col items-center justify-center min-h-[50vh] text-center space-y-8 animate-in fade-in duration-300">
              <div className="flex flex-col items-center space-y-3">
                <div className="h-12 w-12 rounded-full bg-[var(--brand)] flex items-center justify-center text-[var(--text-on-brand)] text-xl font-bold">
                  ⊗
                </div>
                <h2 className="text-[26px] font-bold tracking-tight text-[var(--text-primary)]">
                  How can I assist with compliance today?
                </h2>
                <p className="text-[var(--text-tertiary)] text-sm max-w-md">
                  VeriUnlearn guarantees verifiable machine unlearning and cryptographic compliance proof generation.
                </p>
              </div>

              {/* Quick Status Metrics Strip */}
              <div className="grid grid-cols-4 gap-2.5 w-full max-w-xl bg-[var(--bg-surface)]/60 border border-[var(--bg-hover)]/60 p-3.5 rounded-xl text-center text-xs">
                <div>
                  <p className="text-[10px] text-[var(--text-tertiary)] font-semibold uppercase tracking-wider">Audit Events</p>
                  <p className="text-base font-bold text-[var(--text-primary)] mt-0.5">{eventCount}</p>
                </div>
                <div className="border-l border-[var(--bg-hover)]/60">
                  <p className="text-[10px] text-[var(--text-tertiary)] font-semibold uppercase tracking-wider">Requests</p>
                  <p className="text-base font-bold text-[var(--text-primary)] mt-0.5">{requestCount}</p>
                </div>
                <div className="border-l border-[var(--bg-hover)]/60">
                  <p className="text-[10px] text-[var(--text-tertiary)] font-semibold uppercase tracking-wider">Pending</p>
                  <p className="text-base font-bold text-[var(--warning)] mt-0.5">{pendingCount}</p>
                </div>
                <div className="border-l border-[var(--bg-hover)]/60">
                  <p className="text-[10px] text-[var(--text-tertiary)] font-semibold uppercase tracking-wider">Completed</p>
                  <p className="text-base font-bold text-[var(--brand)] mt-0.5">{completedCount}</p>
                </div>
              </div>

              {/* Prompt Suggestions Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 w-full">
                {promptSuggestions.map((prompt) => (
                  <button
                    key={prompt.title}
                    onClick={() => handleSendMessage(prompt.action)}
                    className="p-4 bg-[var(--bg-surface)]/30 hover:bg-[var(--bg-hover)]/40 border border-[var(--bg-hover)]/60 hover:border-[var(--border-strong)] rounded-xl text-left transition-all group cursor-pointer"
                  >
                    <p className="text-sm font-semibold text-[var(--text-primary)] group-hover:text-[var(--brand)] transition-colors">
                      {prompt.title}
                    </p>
                    <p className="text-xs text-[var(--text-tertiary)] mt-1">
                      {prompt.subtitle}
                    </p>
                  </button>
                ))}
              </div>
            </div>
          ) : (
            // Active Chat Conversation
            <div className="space-y-6 animate-in fade-in duration-300">
              {/* Header options inside chat */}
              <div className="flex justify-between items-center border-b border-[var(--bg-hover)]/50 pb-4 shrink-0">
                <div className="flex items-center gap-2 text-xs text-[var(--text-tertiary)]">
                  <Activity className="h-4 w-4 text-[var(--brand)]" />
                  <span>Compliance Audit Chat Session</span>
                </div>
                <button
                  onClick={handleResetChat}
                  className="flex items-center gap-1 px-2.5 py-1 text-xs bg-[var(--bg-hover)] hover:bg-[var(--bg-hover)]/80 text-[var(--text-primary)] rounded-lg border border-[var(--bg-hover)] hover:border-[var(--border-strong)] transition-all cursor-pointer"
                >
                  <Plus className="h-3.5 w-3.5" />
                  New Chat
                </button>
              </div>

              {/* Message List */}
              <div className="space-y-6">
                {messages.map((msg) => (
                  <div
                    key={msg.id}
                    className={`flex items-start gap-4 ${
                      msg.sender === "user" ? "justify-end" : "justify-start"
                    }`}
                  >
                    {msg.sender === "assistant" && (
                      <div className="h-8 w-8 rounded-full bg-[var(--brand)] flex items-center justify-center text-[var(--text-on-brand)] text-sm font-bold shrink-0">
                        ⊗
                      </div>
                    )}

                    <div
                      className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                        msg.sender === "user"
                          ? "bg-[var(--bg-hover)] text-[var(--text-primary)]"
                          : "text-[var(--text-secondary)]"
                      }`}
                    >
                      <div className="whitespace-pre-wrap">{msg.text}</div>

                      {/* Display Cryptographic Proof if attached */}
                      {msg.proof && (
                        <div className="mt-4 p-4 bg-[var(--bg-surface)] border border-[var(--bg-hover)] rounded-xl font-mono text-[11px] text-[var(--text-secondary)] space-y-2 select-all relative overflow-x-auto">
                          <div className="flex justify-between items-center text-[10px] text-[var(--brand)] uppercase tracking-wider font-semibold border-b border-[var(--bg-hover)] pb-1.5 mb-2.5">
                            <span className="flex items-center gap-1.5">
                              <ShieldCheck className="h-3.5 w-3.5" />
                              Cryptographic Deletion Proof
                            </span>
                            <span className="bg-[var(--brand-soft)] text-[var(--brand-strong)] px-2 py-0.5 rounded-full border border-[var(--brand-border)]">
                              {msg.proof.status}
                            </span>
                          </div>
                          <div>
                            <span className="text-[var(--text-tertiary)]">Root Hash:</span> {msg.proof.root}
                          </div>
                          <div>
                            <span className="text-[var(--text-tertiary)]">Signature:</span> {msg.proof.signature}
                          </div>
                          <div>
                            <span className="text-[var(--text-tertiary)]">Algorithm:</span> {msg.proof.algorithm}
                          </div>
                        </div>
                      )}
                    </div>

                    {msg.sender === "user" && (
                      <div className="h-8 w-8 rounded-full bg-[var(--accent)] flex items-center justify-center text-[var(--text-on-brand)] text-[11px] font-semibold uppercase shrink-0">
                        {user.full_name.substring(0, 2)}
                      </div>
                    )}
                  </div>
                ))}

                {isTyping && (
                  <div className="flex items-start gap-4">
                    <div className="h-8 w-8 rounded-full bg-[var(--brand)] flex items-center justify-center text-[var(--text-on-brand)] text-sm font-bold shrink-0">
                      ⊗
                    </div>
                    <div className="bg-transparent text-[var(--text-tertiary)] text-sm py-2 px-1 flex items-center gap-1.5">
                      <div className="h-1.5 w-1.5 bg-[var(--text-tertiary)] rounded-full animate-bounce" style={{ animationDelay: "0ms" }}></div>
                      <div className="h-1.5 w-1.5 bg-[var(--text-tertiary)] rounded-full animate-bounce" style={{ animationDelay: "150ms" }}></div>
                      <div className="h-1.5 w-1.5 bg-[var(--text-tertiary)] rounded-full animate-bounce" style={{ animationDelay: "300ms" }}></div>
                    </div>
                  </div>
                )}

                <div ref={messagesEndRef} />
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Persistent Bottom Chat Input Area */}
      <div className="absolute bottom-0 left-0 right-0 bg-[var(--bg-app)] px-4 py-4 md:px-0 shrink-0">
        <div className="max-w-2xl mx-auto space-y-3">
          <form
            onSubmit={(e) => {
              e.preventDefault()
              handleSendMessage(inputMessage)
            }}
            className="relative bg-[var(--bg-surface)] border border-[var(--bg-hover)] focus-within:border-[var(--border-strong)] rounded-2xl p-1.5 pr-3 shadow-xl transition-all"
          >
            <div className="flex items-center">
              {/* Paperclip attachment simulation */}
              <button
                type="button"
                className="p-2.5 text-[var(--text-tertiary)] hover:text-[var(--text-primary)] rounded-xl hover:bg-[var(--bg-hover)]/60 transition-colors"
                title="Attach logs or metadata"
              >
                <Paperclip className="h-5 w-5" />
              </button>

              <textarea
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault()
                    handleSendMessage(inputMessage)
                  }
                }}
                placeholder="Message VeriUnlearn Assistant (e.g. 'Initiate deletion request' or 'How do I verify proofs?')"
                rows={1}
                className="flex-1 bg-transparent text-sm text-[var(--text-primary)] placeholder-[var(--text-tertiary)] focus:outline-none resize-none py-2.5 px-3 min-h-[40px] max-h-[200px]"
              />

              {/* Web search toggle simulation */}
              <button
                type="button"
                className="p-2.5 text-[var(--text-tertiary)] hover:text-[var(--text-primary)] rounded-xl hover:bg-[var(--bg-hover)]/60 transition-colors"
                title="Search logs history"
              >
                <Globe className="h-5 w-5" />
              </button>

              <button
                type="submit"
                disabled={!inputMessage.trim()}
                className={`p-2.5 rounded-xl ml-1 transition-all ${
                  inputMessage.trim()
                  ? "bg-[var(--text-primary)] text-[var(--bg-surface)] hover:opacity-90 cursor-pointer"
                  : "bg-[var(--bg-hover)] text-[var(--text-tertiary)] cursor-not-allowed"
                }`}
              >
                <Send className="h-4 w-4" />
              </button>
            </div>
          </form>

          {/* Security Recommendation Warning if MFA disabled */}
          {!user.mfa_enabled && !chatActive && (
            <div className="flex items-center justify-between p-3 bg-[var(--warning-soft)] border border-[var(--warning-border)] rounded-xl text-xs text-[var(--warning)] max-w-xl mx-auto shadow-sm">
              <span className="flex items-center gap-2">
                <AlertCircle className="h-4 w-4 shrink-0 text-[var(--warning)]" />
                MFA is currently disabled. Enable two-factor authentication to secure your audits.
              </span>
              <button
                onClick={() => router.push("/auth/mfa/setup")}
                className="px-2.5 py-1 bg-[var(--warning-soft)] hover:opacity-90 border border-[var(--warning-border)] text-[var(--warning)] font-medium rounded-lg transition-all shrink-0 cursor-pointer"
              >
                Enable
              </button>
            </div>
          )}

          <p className="text-[11px] text-[var(--text-tertiary)] text-center max-w-md mx-auto leading-relaxed">
            VeriUnlearn uses SISA retraining and cryptographic commitments to guarantee deletion. Verification keys are signed via Ed25519.
          </p>
        </div>
      </div>
    </div>
  )
}
