apiVersion: v1
kind: Service
metadata:
  name: ml-engine
  namespace: veriunlearn
  labels:
    app.kubernetes.io/name: veriunlearn
    app.kubernetes.io/component: ml-engine
    app.kubernetes.io/part-of: veriunlearn
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: veriunlearn
    app.kubernetes.io/component: ml-engine
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
