apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: veriunlearn
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          env:
            - name: WORKERS
              value: "4"
            - name: MAX_CONNECTIONS
              value: "100"
