"""phase7 enterprise platform

Revision ID: 10a9fd591a22
Revises: e3bb87e588e3
Create Date: 2026-08-16 22:31:18.548378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a9fd591a22'
down_revision: Union[str, None] = 'e3bb87e588e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_cache'))
    )
    op.create_index(op.f('ix_analytics_cache_cache_key'), 'analytics_cache', ['cache_key'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('quota_per_minute', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_count', sa.Integer(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('compliance_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gdpr_score', sa.Float(), nullable=False),
    sa.Column('gdpr_status', sa.String(length=32), nullable=False),
    sa.Column('dpdp_score', sa.Float(), nullable=False),
    sa.Column('dpdp_status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('open_requests', sa.Integer(), nullable=False),
    sa.Column('completed_requests', sa.Integer(), nullable=False),
    sa.Column('certs_valid', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_reports'))
    )
    op.create_index(op.f('ix_compliance_reports_created_at'), 'compliance_reports', ['created_at'], unique=False)
    op.create_table('deployment_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('artifact', sa.String(length=255), nullable=True),
    sa.Column('deployed_by', sa.String(length=128), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_logs'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_metrics'))
    )
    op.create_index(op.f('ix_system_metrics_name'), 'system_metrics', ['name'], unique=False)
    op.create_index(op.f('ix_system_metrics_sampled_at'), 'system_metrics', ['sampled_at'], unique=False)
    # ### end Alembic commands ###

    # --- Seed RBAC roles + permissions (single source of truth: app/core/rbac.py) ---
    import uuid
    from datetime import datetime, timezone
    from app.core.rbac import ROLE_PERMISSIONS

    # Columns are ``DateTime()`` => ``TIMESTAMP WITHOUT TIME ZONE`` in
    # PostgreSQL; store naive UTC so asyncpg's executemany (bulk_insert)
    # does not reject mixed offset-aware/naive datetimes.
    _now = datetime.now(timezone.utc).replace(tzinfo=None)
    roles_table = sa.table(
        'roles',
        sa.column('id', sa.String(36)),
        sa.column('name', sa.String(32)),
        sa.column('description', sa.Text()),
        sa.column('permissions', sa.JSON()),
        sa.column('created_at', sa.DateTime()),
    )
    op.bulk_insert(
        roles_table,
        [
            {
                'id': str(uuid.uuid4()),
                'name': role,
                'description': f'{role} role (Phase 7 RBAC matrix)',
                'permissions': perms,
                'created_at': _now,
            }
            for role, perms in ROLE_PERMISSIONS.items()
        ],
    )

    permissions_table = sa.table(
        'permissions',
        sa.column('id', sa.String(36)),
        sa.column('name', sa.String(64)),
        sa.column('description', sa.Text()),
        sa.column('category', sa.String(32)),
        sa.column('created_at', sa.DateTime()),
    )
    all_permissions = sorted({p for perms in ROLE_PERMISSIONS.values() for p in perms})
    op.bulk_insert(
        permissions_table,
        [
            {
                'id': str(uuid.uuid4()),
                'name': perm,
                'description': f'Grants {perm}',
                'category': perm.split(':')[0],
                'created_at': _now,
            }
            for perm in all_permissions
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_metrics_sampled_at'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_name'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('deployment_logs')
    op.drop_index(op.f('ix_compliance_reports_created_at'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_analytics_cache_cache_key'), table_name='analytics_cache')
    op.drop_table('analytics_cache')
    # ### end Alembic commands ###
