"""phase5 verifiable unlearning

Revision ID: 203c60186717
Revises: 97fe9443fb40
Create Date: 2026-08-16 21:22:10.544508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203c60186717'
down_revision: Union[str, None] = '97fe9443fb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_proofs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proof_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('claim', sa.String(length=255), nullable=False),
    sa.Column('pre_merkle_root', sa.String(length=64), nullable=False),
    sa.Column('post_merkle_root', sa.String(length=64), nullable=False),
    sa.Column('leaf_hashes', sa.JSON(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('scheme', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crypto_proofs'))
    )
    op.create_index(op.f('ix_crypto_proofs_proof_id'), 'crypto_proofs', ['proof_id'], unique=True)
    op.create_index(op.f('ix_crypto_proofs_subject_id'), 'crypto_proofs', ['subject_id'], unique=False)
    op.create_table('verification_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('certificate_id', sa.String(length=36), nullable=False),
    sa.Column('deletion_request_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('checks_passed', sa.Integer(), nullable=False),
    sa.Column('checks_total', sa.Integer(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('merkle_snapshot', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_reports'))
    )
    op.create_index(op.f('ix_verification_reports_certificate_id'), 'verification_reports', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_verification_reports_dataset_id'), 'verification_reports', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_reports_dataset_id'), table_name='verification_reports')
    op.drop_index(op.f('ix_verification_reports_certificate_id'), table_name='verification_reports')
    op.drop_table('verification_reports')
    op.drop_index(op.f('ix_crypto_proofs_subject_id'), table_name='crypto_proofs')
    op.drop_index(op.f('ix_crypto_proofs_proof_id'), table_name='crypto_proofs')
    op.drop_table('crypto_proofs')
    # ### end Alembic commands ###
