"""initial_schema

Revision ID: 885abc4702e4
Revises: 
Create Date: 2026-07-11 23:41:28.281196
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '885abc4702e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_ledger_event_type'), 'audit_ledger', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_ledger_id'), 'audit_ledger', ['id'], unique=False)
    op.create_table('training_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_datasets_id'), 'training_datasets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('shard_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_shard_id'), 'users', ['shard_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('base_model', sa.String(length=256), nullable=False),
    sa.Column('adapter_path', sa.String(length=512), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('eval_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['training_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_table('unlearning_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlearning_requests_id'), 'unlearning_requests', ['id'], unique=False)
    op.create_index(op.f('ix_unlearning_requests_user_id'), 'unlearning_requests', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('model_shards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('shard_id', sa.String(length=64), nullable=False),
    sa.Column('adapter_path', sa.String(length=512), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_shards_id'), 'model_shards', ['id'], unique=False)
    op.create_index(op.f('ix_model_shards_model_version_id'), 'model_shards', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_model_shards_shard_id'), 'model_shards', ['shard_id'], unique=False)
    op.create_table('unlearning_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('model_version_before_id', sa.Integer(), nullable=True),
    sa.Column('model_version_after_id', sa.Integer(), nullable=True),
    sa.Column('mia_before_accuracy', sa.Float(), nullable=True),
    sa.Column('mia_before_precision', sa.Float(), nullable=True),
    sa.Column('mia_before_recall', sa.Float(), nullable=True),
    sa.Column('mia_before_confidence', sa.Float(), nullable=True),
    sa.Column('mia_after_accuracy', sa.Float(), nullable=True),
    sa.Column('mia_after_precision', sa.Float(), nullable=True),
    sa.Column('mia_after_recall', sa.Float(), nullable=True),
    sa.Column('mia_after_confidence', sa.Float(), nullable=True),
    sa.Column('utility_accuracy', sa.Float(), nullable=True),
    sa.Column('utility_precision', sa.Float(), nullable=True),
    sa.Column('utility_recall', sa.Float(), nullable=True),
    sa.Column('utility_f1', sa.Float(), nullable=True),
    sa.Column('utility_loss', sa.Float(), nullable=True),
    sa.Column('utility_retention', sa.Float(), nullable=True),
    sa.Column('weight_distance', sa.Float(), nullable=True),
    sa.Column('gradient_distance', sa.Float(), nullable=True),
    sa.Column('cosine_similarity', sa.Float(), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('merkle_root', sa.String(length=128), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('certificate_path', sa.String(length=512), nullable=True),
    sa.Column('certificate_hash', sa.String(length=128), nullable=True),
    sa.Column('deletion_latency_ms', sa.Float(), nullable=True),
    sa.Column('privacy_leakage', sa.Float(), nullable=True),
    sa.Column('attack_success_rate_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_after_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_before_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['unlearning_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlearning_results_id'), 'unlearning_results', ['id'], unique=False)
    op.create_index(op.f('ix_unlearning_results_request_id'), 'unlearning_results', ['request_id'], unique=True)
    op.create_table('training_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shard_id', sa.String(length=64), nullable=True),
    sa.Column('slice_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['training_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_samples_dataset_id'), 'training_samples', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_training_samples_id'), 'training_samples', ['id'], unique=False)
    op.create_index(op.f('ix_training_samples_shard_id'), 'training_samples', ['shard_id'], unique=False)
    op.create_index(op.f('ix_training_samples_slice_id'), 'training_samples', ['slice_id'], unique=False)
    op.create_index(op.f('ix_training_samples_user_id'), 'training_samples', ['user_id'], unique=False)
    op.create_table('unlearning_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('training_sample_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['unlearning_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_sample_id'], ['training_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlearning_samples_id'), 'unlearning_samples', ['id'], unique=False)
    op.create_index(op.f('ix_unlearning_samples_request_id'), 'unlearning_samples', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unlearning_samples_request_id'), table_name='unlearning_samples')
    op.drop_index(op.f('ix_unlearning_samples_id'), table_name='unlearning_samples')
    op.drop_table('unlearning_samples')
    op.drop_index(op.f('ix_training_samples_user_id'), table_name='training_samples')
    op.drop_index(op.f('ix_training_samples_slice_id'), table_name='training_samples')
    op.drop_index(op.f('ix_training_samples_shard_id'), table_name='training_samples')
    op.drop_index(op.f('ix_training_samples_id'), table_name='training_samples')
    op.drop_index(op.f('ix_training_samples_dataset_id'), table_name='training_samples')
    op.drop_table('training_samples')
    op.drop_index(op.f('ix_unlearning_results_request_id'), table_name='unlearning_results')
    op.drop_index(op.f('ix_unlearning_results_id'), table_name='unlearning_results')
    op.drop_table('unlearning_results')
    op.drop_index(op.f('ix_model_shards_shard_id'), table_name='model_shards')
    op.drop_index(op.f('ix_model_shards_model_version_id'), table_name='model_shards')
    op.drop_index(op.f('ix_model_shards_id'), table_name='model_shards')
    op.drop_table('model_shards')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_unlearning_requests_user_id'), table_name='unlearning_requests')
    op.drop_index(op.f('ix_unlearning_requests_id'), table_name='unlearning_requests')
    op.drop_table('unlearning_requests')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_shard_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_datasets_id'), table_name='training_datasets')
    op.drop_table('training_datasets')
    op.drop_index(op.f('ix_audit_ledger_id'), table_name='audit_ledger')
    op.drop_index(op.f('ix_audit_ledger_event_type'), table_name='audit_ledger')
    op.drop_table('audit_ledger')
    # ### end Alembic commands ###
