"""phase3 privacy auditor + phase4 surgical unlearning

Revision ID: 97fe9443fb40
Revises: bd3d39814aa2
Create Date: 2026-08-16 20:54:02.165069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fe9443fb40'
down_revision: Union[str, None] = 'bd3d39814aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('shard_ids', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_version', sa.Integer(), nullable=True),
    sa.Column('records_before', sa.Integer(), nullable=False),
    sa.Column('records_after', sa.Integer(), nullable=False),
    sa.Column('embeddings_before', sa.Integer(), nullable=False),
    sa.Column('embeddings_after', sa.Integer(), nullable=False),
    sa.Column('vectors_removed', sa.Integer(), nullable=False),
    sa.Column('certified_bound', sa.Float(), nullable=True),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_history'))
    )
    op.create_index(op.f('ix_deletion_history_request_id'), 'deletion_history', ['request_id'], unique=False)
    op.create_table('embedding_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('embedding_id', sa.String(length=128), nullable=False),
    sa.Column('vector_id', sa.String(length=128), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_index'))
    )
    op.create_index(op.f('ix_embedding_index_dataset_id'), 'embedding_index', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_embedding_index_embedding_id'), 'embedding_index', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_embedding_index_record_id'), 'embedding_index', ['record_id'], unique=False)
    op.create_table('identity_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_key', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('aadhaar', sa.String(length=64), nullable=False),
    sa.Column('pan', sa.String(length=64), nullable=False),
    sa.Column('passport', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('dob', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('dataset_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_index'))
    )
    op.create_index(op.f('ix_identity_index_identity_key'), 'identity_index', ['identity_key'], unique=True)
    op.create_table('privacy_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('scanned_records', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_reports'))
    )
    op.create_index(op.f('ix_privacy_reports_dataset_id'), 'privacy_reports', ['dataset_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.add_column('dataset_records', sa.Column('phone_enc', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('aadhaar_enc', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('pan_enc', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('passport_enc', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('dob_enc', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('address_enc', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('chat_id', sa.String(length=128), nullable=True))
    op.add_column('dataset_records', sa.Column('source_filename', sa.String(length=512), nullable=True))
    op.add_column('dataset_records', sa.Column('source_timestamp', sa.DateTime(), nullable=True))
    op.add_column('dataset_records', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.add_column('dataset_records', sa.Column('original_text', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('vector_id', sa.String(length=128), nullable=True))
    op.create_index('ix_records_chat', 'dataset_records', ['chat_id'], unique=False)
    op.add_column('datasets', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'version')
    op.drop_index('ix_records_chat', table_name='dataset_records')
    op.drop_column('dataset_records', 'vector_id')
    op.drop_column('dataset_records', 'original_text')
    op.drop_column('dataset_records', 'chunk_index')
    op.drop_column('dataset_records', 'source_timestamp')
    op.drop_column('dataset_records', 'source_filename')
    op.drop_column('dataset_records', 'chat_id')
    op.drop_column('dataset_records', 'address_enc')
    op.drop_column('dataset_records', 'dob_enc')
    op.drop_column('dataset_records', 'passport_enc')
    op.drop_column('dataset_records', 'pan_enc')
    op.drop_column('dataset_records', 'aadhaar_enc')
    op.drop_column('dataset_records', 'phone_enc')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_privacy_reports_dataset_id'), table_name='privacy_reports')
    op.drop_table('privacy_reports')
    op.drop_index(op.f('ix_identity_index_identity_key'), table_name='identity_index')
    op.drop_table('identity_index')
    op.drop_index(op.f('ix_embedding_index_record_id'), table_name='embedding_index')
    op.drop_index(op.f('ix_embedding_index_embedding_id'), table_name='embedding_index')
    op.drop_index(op.f('ix_embedding_index_dataset_id'), table_name='embedding_index')
    op.drop_table('embedding_index')
    op.drop_index(op.f('ix_deletion_history_request_id'), table_name='deletion_history')
    op.drop_table('deletion_history')
    # ### end Alembic commands ###
