"""initial schema

Revision ID: bd3d39814aa2
Revises: 
Create Date: 2026-08-16 20:53:51.869970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3d39814aa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('blockchain_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('certificate_id', sa.String(length=36), nullable=False),
    sa.Column('cert_hash', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=64), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_ledger')),
    sa.UniqueConstraint('certificate_id', name='uq_ledger_cert')
    )
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deletion_request_id', sa.String(length=36), nullable=True),
    sa.Column('subject_user_id', sa.String(length=128), nullable=False),
    sa.Column('deletion_type', sa.String(length=64), nullable=False),
    sa.Column('deleted_record_count', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('shard_ids', sa.JSON(), nullable=False),
    sa.Column('pre_merkle_root', sa.String(length=64), nullable=False),
    sa.Column('post_merkle_root', sa.String(length=64), nullable=False),
    sa.Column('deleted_record_hashes', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('certified_bound', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('certificate_json', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('zk_proof', sa.JSON(), nullable=False),
    sa.Column('blockchain_tx', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('label_column', sa.String(length=255), nullable=True),
    sa.Column('shard_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_table('deletion_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_key', sa.String(length=128), nullable=True),
    sa.Column('subject_label', sa.String(length=255), nullable=False),
    sa.Column('deletion_type', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('record_ids', sa.JSON(), nullable=False),
    sa.Column('shard_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('certificate_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_requests'))
    )
    op.create_index(op.f('ix_deletion_requests_identity_key'), 'deletion_requests', ['identity_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dataset_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('record_index', sa.Integer(), nullable=False),
    sa.Column('shard_id', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('label', sa.JSON(), nullable=True),
    sa.Column('identity_key', sa.String(length=128), nullable=True),
    sa.Column('full_name_enc', sa.Text(), nullable=True),
    sa.Column('email_enc', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('tombstone_hash', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('embedding_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_records_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_records'))
    )
    op.create_index(op.f('ix_dataset_records_dataset_id'), 'dataset_records', ['dataset_id'], unique=False)
    op.create_index('ix_records_identity', 'dataset_records', ['identity_key'], unique=False)
    op.create_index('ix_records_shard', 'dataset_records', ['dataset_id', 'shard_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('shard_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('weights_hash', sa.String(length=64), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('aggregation', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('adapters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_ml_models_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models'))
    )
    op.create_index(op.f('ix_ml_models_dataset_id'), 'ml_models', ['dataset_id'], unique=False)
    op.create_table('model_shards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('shard_index', sa.Integer(), nullable=False),
    sa.Column('weights_path', sa.String(length=512), nullable=True),
    sa.Column('weights_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('retrained_at', sa.DateTime(), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('trained_on', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name=op.f('fk_model_shards_model_id_ml_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_shards'))
    )
    op.create_index(op.f('ix_model_shards_model_id'), 'model_shards', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_shards_model_id'), table_name='model_shards')
    op.drop_table('model_shards')
    op.drop_index(op.f('ix_ml_models_dataset_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index('ix_records_shard', table_name='dataset_records')
    op.drop_index('ix_records_identity', table_name='dataset_records')
    op.drop_index(op.f('ix_dataset_records_dataset_id'), table_name='dataset_records')
    op.drop_table('dataset_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_deletion_requests_identity_key'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_table('datasets')
    op.drop_table('certificates')
    op.drop_table('blockchain_ledger')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
